[package]
name = "maths-ia"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
rayon = "1.10.0"
indicatif = { version = "0.17.8", features = ["rayon"] }
